### ISSUE TITLE
Send To Slack Channel(s) or Direct Message(s) options must be explictly set

### ISSUE THREAD

**Issue by ntwb** [bamadesigner/rock-the-slackbot#10]
Without setting a channel e.g. `#test` in the `Send To Slack Channel(s) or Direct Message(s)` option no notifications are received in Slack regardless of the fact that `#test` is set in the Slack webhook on slack.com

Here's a few scenarios that all failed until I set `#test` as the channel in the `Send To Slack Channel(s) or Direct Message(s)` option:

• 404, once I added `#test` to the option the 404's option it worked, it also works as expected by removing the channel from the 404's optional channel setting and using the 'parent'  `Send To Slack Channel(s) or Direct Message(s)` option.

• Custom post types, once I added `#test` to `Send To Slack Channel(s) or Direct Message(s)` then various post types worked as epected

• The `Test this webhook` also fails without the option set, it returns that the test was successful but no notifications are received in the Slack channel. Once adding the channel to the option the test now works as expected and a notification is seen in the Slack channel.

**Comment by bamadesigner** [comment]
Hi! I apologize for the much delayed response. All is fixed and will go out in the next release. Thanks!
