### ISSUE TITLE
Add support for "translation updates"

### ISSUE THREAD

**Issue by ntwb** [bamadesigner/rock-the-slackbot#11]
Along with core, plugin, and theme updates it would be great see translation updates added.

I just made English (Australian) 100% translated so a "language pack" should become available within ~24 hours.

https://translate.wordpress.org/locale/en-au/default/wp-plugins/rock-the-slackbot

https://api.wordpress.org/translations/plugins/1.0/?slug=rock-the-slackbot&version=1.1.1

**Comment by bamadesigner** [comment]
I've added a few languages to the mix! Thanks!
