### ISSUE TITLE
"Cancelling" a notification later in the process

### ISSUE THREAD

**Issue by helen** [bamadesigner/rock-the-slackbot#19]
I do some notification customization using the `rock_the_slackbot_notification` hook but there does not appear to be a way for me to decide from within there to not send a notification at all, as returning an empty payload ends up merged with a default payload (which seems odd, by the way). Specifically, what I want to do is only send notifications for posts of the post post type for a given outgoing setup - I know this can be set in the plugin's UI settings, but since it's opt-out instead of opt-in we frequently have problems with new post types suddenly appearing and en masse because of an import or similar, so I'd rather enforce it in code. Is there something I'm missing that I could do instead?

**Comment by bamadesigner** [comment]
I just pushed out an update and tweaked it so if you return anything empty to the filter it will cancel sending the notification. Thanks!
