### ISSUE TITLE
Notification not received if channel field left empty

### ISSUE THREAD

**Issue by lumpysimon** [bamadesigner/rock-the-slackbot#4]
Not a major issue, but If I set up a webhook on Slack and specify the channel, and then leave the `Send To Slack Channel or Direct Message` field empty (to use the default channel) on the Rock the Slackbot config, the notification is not received. When I specify a channel or direct message, then everything works fine.

**Comment by bamadesigner** [comment]
Hi! Thanks for the heads up! Yes. I figured this out as I was working on the next release. Hope to have it out in the next week or two. Thanks again!
