### ISSUE TITLE
Broken application of filters?

### ISSUE THREAD

**Issue by ajaleelp** [bamadesigner/rock-the-slackbot#5]
https://github.com/bamadesigner/rock-the-slackbot/blob/master/includes/hooks.php#L153-L157
1. It appears that the code never invokes the first filter applicable for _all notifications_ (`rock_the_slackbot_notification`) 
2. The filter with `hook ID` specified appears to be accepting a _fresh copy_ of `$payload` , hence _overwriting_ the result of previous filter (`rock_the_slackbot_notification_{$notification_event}`). Shouldn't the result of the first filter be supplied to the second and so on?

**Comment by bamadesigner** [comment]
You're right! Thanks for the heads up! I've got it fixed for the next version, which you can see in the develop branch: https://github.com/bamadesigner/rock-the-slackbot/blob/develop/includes/hooks.php#L155-L165
